### PR TITLE
Update TLD max length to 10 for email validation

### PR DESCRIPTION
**Pull request by jeffu**
This is to add support for longer TLDs like .ventures and .diamonds

### CODE REVIEW

**Comment by cmaron** [comment]
What about .சிங்கப்பூர்?

**Comment by jeffreylo** [comment]
@cmaron, pls

**Comment by adam410** [comment]
CHAD'S HERE!?

**Comment by cmaron** [comment]
Apparently. I got an email about Jeff U's commit and was like whoa.

**Comment by jeffreylo** [comment]
`.warbyparker`

**Comment by jeffu** [comment]
Would it be premature to just up it to 63 characters? http://en.wikipedia.org/wiki/Domain_Name_System#cite_ref-rfc1034_1-2

**Pull request merged**
